/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface CedarChart {
        "cedarUrl": string;
        "configUrl": string;
    }
    interface CedarTable {
    }
}
declare global {
    interface HTMLCedarChartElement extends Components.CedarChart, HTMLStencilElement {
    }
    var HTMLCedarChartElement: {
        prototype: HTMLCedarChartElement;
        new (): HTMLCedarChartElement;
    };
    interface HTMLCedarTableElement extends Components.CedarTable, HTMLStencilElement {
    }
    var HTMLCedarTableElement: {
        prototype: HTMLCedarTableElement;
        new (): HTMLCedarTableElement;
    };
    interface HTMLElementTagNameMap {
        "cedar-chart": HTMLCedarChartElement;
        "cedar-table": HTMLCedarTableElement;
    }
}
declare namespace LocalJSX {
    interface CedarChart {
        "cedarUrl"?: string;
        "configUrl"?: string;
    }
    interface CedarTable {
    }
    interface IntrinsicElements {
        "cedar-chart": CedarChart;
        "cedar-table": CedarTable;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cedar-chart": LocalJSX.CedarChart & JSXBase.HTMLAttributes<HTMLCedarChartElement>;
            "cedar-table": LocalJSX.CedarTable & JSXBase.HTMLAttributes<HTMLCedarTableElement>;
        }
    }
}
